# |------------------------------------------|
# | This file is autogenerated. Do not edit! |
# |------------------------------------------|
# ~/.bashrc

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Make less more friendly for non-text input files
[[ -x /usr/bin/lesspipe ]] && eval "$(SHELL=/bin/sh lesspipe)"

# Enable color support
[[ -x /usr/bin/dircolors ]] && eval "$(dircolors -b)"

# Clear history after exiting {{{
clr_hist() {
    clear
    reset
    history -c
    history -w
}

trap clr_hist EXIT
# }}}

# Sourcing {{{
# Functions
[[ -f ~/.config/bash/bash_funcs ]] && . ~/.config/bash/bash_funcs

# Aliases
[[ -f ~/.config/bash/bash_aliases ]] && . ~/.config/bash/bash_aliases

# Completions
[[ -d ~/.config/bash/bash_completions ]] && . ~/.config/bash/bash_completions/*

# Command not found
. /usr/share/doc/pkgfile/command-not-found.bash
# }}}

# Variables {{{
# Don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# Set history length.
HISTFILESIZE=2000
HISTSIZE=1000

# Colored GCC warnings and errors.
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# Disable .NET telemetry
export DOTNET_CLI_TELEMETRY_OPTOUT=1

export EDITOR="nvim -u ~/.config/nvim/vi_init.lua --noplugins"
export VISUAL="nvim -u ~/.config/nvim/vim_init.lua"
export SUDO_EDITOR="$EDITOR"
# }}}

# Prompt {{{
RED=$(tput setaf 1) # Red
GRN=$(tput setaf 2) # Green
YEL=$(tput setaf 3) # Yellow
BLU=$(tput setaf 4) # Blue
MAG=$(tput setaf 5) # Magenta
CYA=$(tput setaf 6) # Cyan
WHT=$(tput setaf 7) # White
BLK=$(tput setaf 8) # Black
# BLK=$(tput setaf 0) # Black wrs

BLD=$(tput bold)    # Bold
UL=$(tput smul)     # Underline
NC=$(tput sgr0)     # No color

PS1='\[$MAG\]┌< \[$BLK$BLD\]$(spwd)\[$NC$MAG\] > \[$RED\]\u\[$WHT\]@\[$RED\]\l \n \[$NC$MAG\]| \[$RED\]\! \[$MAG\]>\[$YEL\] \$ \[$NC\]'

# Old prompts
# PS1='\[$MAG\]┌< \[$BLU$BLD\]$(spwd) \[$MAG\]> \[$RED\]\u\[$NC\]@\[$RED\]\l \n\[$MAG\]└< \[$RED\]\! \[$MAG\]>\[$YEL\] \$ \[$NC\]'
#                 r   g   b
# PS1=' \[\e[38;2;148;0;211m\]\[\e[97;48;2;148;0;211m\] $(spwd) \[\e[0;38;2;148;0;211m\] \[\e[38;2;131;111;255m\]\u\[\e[38;2;224;102;255m\]\$ \[\e[0m\]'
# PS1='\[\e[30;48;5;81;1m\] $(spwd) \[\e[0;38;5;81;48;5;86m\]\[\e[30;1m\] \u \[\e[0;38;5;86;48;5;140m\]\[\e[30;1m\] \$ \[\e[0;38;5;140m\] \[\e[0m\]'
# PS1='\[\e[30;48;5;81;1m\] $(spwd) \[\e[0;38;5;81;48;5;86m\]\[\e[30;1m\] \u \[\e[0;38;5;86;48;5;140m\]\[\e[30;1m\] \$ \[\e[0;38;5;140m\] \[\e[0m\]'
# }}}

# Config {{{
shopt -s checkwinsize
shopt -s histappend
shopt -s globstar
shopt -s cdspell
shopt -s autocd

set -o noclobber
set -o vi
# }}}

if [[ $(tty) = *tty* ]]; then
    echo "tty detected, no annoying messages"
    return
fi

# ssh agent. {{{
env=~/.ssh/agent.env

agent_load_env () {
    test -f "$env" && . "$env" >| /dev/null ;
}

agent_start () {
    (umask 077; ssh-agent >| "$env")
    . "$env" >| /dev/null ;
}
agent_load_env

# agent_run_state: 0 agent running w/ key; 1 agent w/o key; 2 agent not running.
agent_run_state=$(ssh-add -l >| /dev/null 2>&1; echo $?)

if [ ! "$SSH_AUTH_SOCK" ] || [ $agent_run_state = 2 ]; then
    agent_start
    ssh-add

elif [ "$SSH_AUTH_SOCK" ] && [ $agent_run_state = 1 ]; then
    ssh-add
fi
# }}}

# To-do {{{
important_count=$(grep -icE 'study|homework|important' ~/.config/please/config.json)
done_count=$(grep -ic '"done": true' ~/.config/please/config.json)
term_count=$(ls /dev/pts/ | grep -vcE '[[:alpha:]]')

if (( $done_count >= 2 )) ; then
    please clean
else
    please
fi

## Read the to-do list warning {{{
if (( $important_count >= 1 )); then
    if (( $important_count > 3)); then
        echo -e "${RED}" \
        '
 _  ______ _____  ___ ______   _____ _   _  _____   _____ _____       ______ _____   _     _____ _____ _____   _ 
| | | ___ \  ___|/ _ \|  _  \ |_   _| | | ||  ___| |_   _|  _  |      |  _  \  _  | | |   |_   _/  ___|_   _| | |
| | | |_/ / |__ / /_\ \ | | |   | | | |_| || |__     | | | | | |______| | | | | | | | |     | | \ `--.  | |   | |
| | |    /|  __||  _  | | | |   | | |  _  ||  __|    | | | | | |______| | | | | | | | |     | |  `--. \ | |   | |
|_| | |\ \| |___| | | | |/ /    | | | | | || |___    | | \ \_/ /      | |/ /\ \_/ / | |_____| |_/\__/ / | |   |_|
(_) \_| \_\____/\_| |_/___/     \_/ \_| |_/\____/    \_/  \___/       |___/  \___/  \_____/\___/\____/  \_/   (_)
        ' \
        "${NC}"
        sleep 3
    else
        echo -e "${RED} ! READ THE TO-DO LIST ! ${NC}"
        sleep 2
    fi
fi
## }}}

## Other to-dos {{{
if (( $term_count <= 2 )); then
    input='n'
    read -p "Do you wish to see other stuff to-do? (y/n): " input

    if [[ $input = [yY]* ]] ; then
        cd ~/notes/to_dos/

        glow
        cd - > /dev/null
    fi
fi
## }}}

# }}}

# Emilly S.H. :D
