#!/bin/bash
# ~/.bash_funcs

# yt-ogg {{{
yt-ogg() {
    tmp=/tmp/tmp.wav
    file_name="${1/\.ogg/}"
    url="$2"

    yt-dlp -x --audio-format wav --audio-quality 0 -o "$tmp" "$url"
    ffmpeg -i "$tmp" "${file_name}.ogg"
    rm "$tmp"
}
# }}}

# mkcd {{{
mkcd () {
    mkdir "$1" && cd "$1"
}
# }}}

# mksh {{{
mksh () {
    arg1="${1//.sh/}.sh"

    touch "$arg1"
    chmod 755 "$arg1"

    echo -e '#!/bin/bash \n' >| "$arg1"
}
# }}}

# Emilly S.H. :D
